### ISSUE TITLE
MUONEFF

### ISSUE THREAD

**Issue by JouvinLea** [gammapy/gammapy-extra#27]
@cdeil @joleroi 
Hi,
In your fits events file example, I don't see the keyword MUONEFF but we agreed that it was necessary to have it right?
I need it to test the grouping,
cheers,
Lea

**Comment by cdeil** [comment]
In the HD-HAP export, we do put `MUONEFF` in the event list header already, and it's also copied to the observation index table.

These event lists don't have `MUONEFF` because they were simulated and the simulation script doesn't copy the full header over:
```
gammapy-extra/datasets/hess-crab4-hd-hap-prod2/run023400-023599/run023523/hess_events_023523.fits.gz
```

So for now you can either take the muon efficiency from the obs index file:
```
gammapy-extra/datasets/hess-crab4-hd-hap-prod2/obs-index.fits.gz
```
or use the real HESS event list example files which are here:
https://github.com/gammasky/hess-host-analyses/tree/master/hap-hd-example-files

OK?

**Comment by JouvinLea** [comment]
For the moment I add the key MUONEFF to you simulated event list in order to use the same as yours for my test!!
Is it possible to copy the keyword MUONEFF for the next time?

**Comment by cdeil** [comment]
@JouvinLea - I'm closing this issue from February now. Feel free to re-open if you want me to do something here.

We should switch Gammapy testing to this set of files in the coming weeks which will resolve the issue of not having MUONEFF set in test files.
https://hess-confluence.desy.de/confluence/display/HESS/HESS+FITS+data+-+HESS+high-level+public+test+data+release+1
